import { Player } from "../freunde/ts/gameState.ts";
const playerArr: Player[] = [
  {
    posX: 480,
    posY: 540,
    velX: Math.random() * 50 - 25,
    velY: 0,
    id: 0,
    ping: 0,
    name: "Hans",
    location: "level",
    color: "#FFA905",
    playerWidth: 64,
    playerHeight: 64,
    playerOffset: 20,
    movementSpeed: 5,
    jumpSpeed: -3,
    dashSpeed: 15,
    resistance: 0.8999,
    gravity: 0.1,
    hitForce: 1.2,
    jumpCooldown: 0,
  },
  {
    posX: 480,
    posY: 540,
    velX: Math.random() * 50 - 25,
    velY: 0,
    id: 0,
    ping: 0,
    name: "Lisa",
    location: "level",
    color: "#FF5400",
    playerWidth: 64,
    playerHeight: 64,
    playerOffset: 20,
    movementSpeed: 5,
    jumpSpeed: -3,
    dashSpeed: 15,
    resistance: 0.8999,
    gravity: 0.1,
    hitForce: 1.2,
    jumpCooldown: 0,
  },
  {
    posX: 480,
    posY: 540,
    velX: Math.random() * 50 - 25,
    velY: 0,
    id: 0,
    ping: 0,
    name: "Karl",
    location: "level",
    color: "#1ED1FF",
    playerWidth: 64,
    playerHeight: 64,
    playerOffset: 20,
    movementSpeed: 5,
    jumpSpeed: -3,
    dashSpeed: 15,
    resistance: 0.8999,
    gravity: 0.1,
    hitForce: 1.2,
    jumpCooldown: 0,
  },
  {
    posX: 480,
    posY: 540,
    velX: Math.random() * 50 - 25,
    velY: 0,
    id: 0,
    ping: 0,
    name: "Anna",
    location: "level",
    color: "#9DED00",
    playerWidth: 64,
    playerHeight: 64,
    playerOffset: 20,
    movementSpeed: 5,
    jumpSpeed: -3,
    dashSpeed: 15,
    resistance: 0.8999,
    gravity: 0.1,
    hitForce: 1.2,
    jumpCooldown: 0,
  },
  {
    posX: 480,
    posY: 540,
    velX: Math.random() * 50 - 25,
    velY: 0,
    id: 0,
    ping: 0,
    name: "Johanna",
    location: "level",
    color: "#F10047",
    playerWidth: 64,
    playerHeight: 64,
    playerOffset: 20,
    movementSpeed: 5,
    jumpSpeed: -3,
    dashSpeed: 15,
    resistance: 0.8999,
    gravity: 0.1,
    hitForce: 1.2,
    jumpCooldown: 0,
  },
];
const colorArr = [
  "#FFA905", // Tokyo Red
  "#FF5400", // Tokyo Gold
  "#1ED1FF", // Tokyo Skyblue
  "#9DED00", // Tokyo Blue
  "#F10047", // Vivid Red-Orange
];
const germanNames: string[] = [
  "Hans",
  "Ursula",
  "Günther",
  "Heidi",
  "Klaus",
  "Annegret",
  "Dieter",
  "Brigitte",
  "Wolfgang",
  "Christa",
];

export function getPlayerFromArr(key: number): Player {
  let player: Player = playerArr[Math.floor(Math.random() * 6) % 5];
  player.id = key;
  player.name = germanNames[Math.floor(Math.random() * germanNames.length)];
  player.color = colorArr[key % 5];
  return player;
}
